resources:
- azure-vote-back-deployment.yaml
- azure-vote-back-service.yaml
- azure-vote-front-deployment.yaml
- azure-vote-front-ingress.yaml
- azure-vote-front-service.yaml
- traefik-ingress-controller-clusterrolebinding.yaml
- traefik-ingress-controller-clusterrole.yaml
- traefik-ingress-controller-deployment.yaml
- traefik-ingress-controller-service-account.yaml
- traefik-ingress-controller-service.yaml
- sealed-secrets-controller-deployment.yaml
- sealed-secrets-crd.yaml
- arango-claim.yaml
- arangodb-deployment.yaml
- arangodb-service.yaml
- arango-secrets.yaml
- cybercrime-api-namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: microsoft/azure-vote-front
  newTag: v1
